<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            // Sports Footwear (cat_id: 1)
            [
                'title' => 'Nike Air Max 270',
                'slug' => 'nike-air-max-270',
                'summary' => 'Lightweight running shoes with Air cushioning.',
                'description' => 'The Nike Air Max 270 offers unparalleled comfort with its large Air unit in the heel, providing exceptional cushioning for running or casual wear. Its breathable mesh upper ensures ventilation, while the durable rubber outsole delivers reliable traction. Perfect for athletes and sneaker enthusiasts alike.',
                'photo' => '',
                'stock' => 30,
                'size' => 'US 9',
                'condition' => 'new',
                'status' => 'active',
                'price' => 150.00,
                'discount' => 15.00,
                'is_featured' => true,
                'cat_id' => 1,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Adidas Ultraboost 22',
                'slug' => 'adidas-ultraboost-22',
                'summary' => 'High-performance running shoes with Boost technology.',
                'description' => 'The Adidas Ultraboost 22 combines energy-returning Boost midsole technology with a Primeknit upper for a snug, adaptive fit. Ideal for long-distance running, these shoes offer superior cushioning and responsiveness, with a Continental rubber outsole for enhanced grip in wet and dry conditions.',
                'photo' => '',
                'stock' => 25,
                'size' => 'US 8',
                'condition' => 'hot',
                'status' => 'active',
                'price' => 180.00,
                'discount' => 10.00,
                'is_featured' => false,
                'cat_id' => 1,
                'child_cat_id' => null,
                'brand_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Under Armour HOVR Phantom',
                'slug' => 'under-armour-hovr-phantom',
                'summary' => 'Comfortable training shoes with HOVR cushioning.',
                'description' => 'The Under Armour HOVR Phantom features HOVR technology for a zero-gravity feel, providing excellent shock absorption and energy return. Its stretchy, sock-like upper ensures a secure fit, while the durable outsole supports versatile training activities, from gym workouts to outdoor sprints.',
                'photo' => '',
                'stock' => 20,
                'size' => 'US 10',
                'condition' => 'default',
                'status' => 'active',
                'price' => 140.00,
                'discount' => 10.00,
                'is_featured' => true,
                'cat_id' => 1,
                'child_cat_id' => null,
                'brand_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nike Zoom Pegasus 39',
                'slug' => 'nike-zoom-pegasus-39',
                'summary' => 'Versatile running shoes for daily training.',
                'description' => 'The Nike Zoom Pegasus 39 is designed for everyday runners, featuring responsive Zoom Air cushioning and a lightweight foam midsole. Its breathable mesh upper promotes airflow, and the rubber outsole provides durability and traction, making it ideal for both short and long runs.',
                'photo' => '',
                'stock' => 35,
                'size' => 'US 8.5',
                'condition' => 'new',
                'status' => 'active',
                'price' => 130.00,
                'discount' => 10.00,
                'is_featured' => false,
                'cat_id' => 1,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Adidas NMD R1',
                'slug' => 'adidas-nmd-r1',
                'summary' => 'Stylish sneakers for casual and athletic use.',
                'description' => 'The Adidas NMD R1 blends style and performance with a stretchy knit upper and Boost cushioning for all-day comfort. Its minimalist design makes it perfect for both casual outings and light athletic activities, with a grippy rubber outsole for stability.',
                'photo' => '',
                'stock' => 15,
                'size' => 'US 9.5',
                'condition' => 'hot',
                'status' => 'active',
                'price' => 140.00,
                'discount' => 20.00,
                'is_featured' => false,
                'cat_id' => 1,
                'child_cat_id' => null,
                'brand_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Under Armour Curry 9',
                'slug' => 'under-armour-curry-9',
                'summary' => 'Basketball shoes designed for agility.',
                'description' => 'The Under Armour Curry 9, inspired by Stephen Curry, offers lightweight construction and responsive cushioning for quick movements on the court. Its reinforced upper provides support, while the grippy outsole ensures excellent traction for sharp cuts and fast breaks.',
                'photo' => '',
                'stock' => 10,
                'size' => 'US 11',
                'condition' => 'default',
                'status' => 'inactive',
                'price' => 160.00,
                'discount' => 10.00,
                'is_featured' => false,
                'cat_id' => 1,
                'child_cat_id' => null,
                'brand_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nike Air Zoom Alphafly',
                'slug' => 'nike-air-zoom-alphafly',
                'summary' => 'Elite running shoes for marathon runners.',
                'description' => 'The Nike Air Zoom Alphafly is built for elite runners, featuring ZoomX foam and two Zoom Air pods for maximum energy return. Its carbon-fiber plate enhances propulsion, and the breathable Atomknit upper reduces weight, making it ideal for marathon and long-distance races.',
                'photo' => '',
                'stock' => 40,
                'size' => 'US 10',
                'condition' => 'new',
                'status' => 'active',
                'price' => 200.00,
                'discount' => 25.00,
                'is_featured' => true,
                'cat_id' => 1,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Adidas Predator Freak',
                'slug' => 'adidas-predator-freak',
                'summary' => 'Soccer boots with enhanced grip.',
                'description' => 'The Adidas Predator Freak soccer boots feature Demonskin technology for superior ball control and swerve. The supportive upper and studded outsole provide stability and traction on the pitch, making these boots perfect for attacking players.',
                'photo' => '',
                'stock' => 28,
                'size' => 'US 9',
                'condition' => 'hot',
                'status' => 'active',
                'price' => 120.00,
                'discount' => 5.00,
                'is_featured' => false,
                'cat_id' => 1,
                'child_cat_id' => null,
                'brand_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Under Armour Flow Velociti',
                'slug' => 'under-armour-flow-velociti',
                'summary' => 'Lightweight running shoes with breathable mesh.',
                'description' => 'The Under Armour Flow Velociti offers a lightweight design with a breathable mesh upper for optimal ventilation. Its innovative Flow technology provides a cushioned yet responsive ride, perfect for runners seeking speed and comfort.',
                'photo' => '',
                'stock' => 22,
                'size' => 'US 8',
                'condition' => 'default',
                'status' => 'active',
                'price' => 130.00,
                'discount' => 15.00,
                'is_featured' => false,
                'cat_id' => 1,
                'child_cat_id' => null,
                'brand_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nike Metcon 7',
                'slug' => 'nike-metcon-7',
                'summary' => 'Training shoes for crossfit and gym workouts.',
                'description' => 'The Nike Metcon 7 is engineered for crossfit and gym training, featuring a stable platform for lifting and flexible forefoot for agility. Its React foam provides cushioning, and the grippy outsole ensures traction during intense workouts.',
                'photo' => '',
                'stock' => 18,
                'size' => 'US 10.5',
                'condition' => 'new',
                'status' => 'active',
                'price' => 135.00,
                'discount' => 5.00,
                'is_featured' => false,
                'cat_id' => 1,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Athletic Apparel (cat_id: 2)
            [
                'title' => 'Nike Dri-FIT T-Shirt',
                'slug' => 'nike-dri-fit-tshirt',
                'summary' => 'Breathable athletic t-shirt for workouts.',
                'description' => 'The Nike Dri-FIT T-Shirt is made with sweat-wicking fabric to keep you dry during intense workouts. Its lightweight, breathable design and relaxed fit make it perfect for running, gym sessions, or casual wear.',
                'photo' => '',
                'stock' => 50,
                'size' => 'M',
                'condition' => 'default',
                'status' => 'active',
                'price' => 35.00,
                'discount' => 5.00,
                'is_featured' => true,
                'cat_id' => 2,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Adidas Techfit Shorts',
                'slug' => 'adidas-techfit-shorts',
                'summary' => 'Compression shorts for enhanced performance.',
                'description' => 'The Adidas Techfit Shorts provide a compressive fit to support muscles during high-intensity activities. Made with moisture-wicking Climalite fabric, these shorts keep you cool and comfortable, ideal for training or team sports.',
                'photo' => '',
                'stock' => 45,
                'size' => 'L',
                'condition' => 'new',
                'status' => 'active',
                'price' => 40.00,
                'discount' => 0,
                'is_featured' => false,
                'cat_id' => 2,
                'child_cat_id' => null,
                'brand_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Under Armour HeatGear Jacket',
                'slug' => 'under-armour-heatgear-jacket',
                'summary' => 'Lightweight jacket for outdoor training.',
                'description' => 'The Under Armour HeatGear Jacket is designed for outdoor athletes, offering lightweight warmth and breathability. Its stretchy fabric allows full range of motion, and the water-resistant coating makes it suitable for light rain conditions.',
                'photo' => '',
                'stock' => 30,
                'size' => 'S',
                'condition' => 'hot',
                'status' => 'active',
                'price' => 60.00,
                'discount' => 10.00,
                'is_featured' => true,
                'cat_id' => 2,
                'child_cat_id' => null,
                'brand_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nike Pro Leggings',
                'slug' => 'nike-pro-leggings',
                'summary' => 'Stretchy leggings for gym and yoga.',
                'description' => 'The Nike Pro Leggings offer a snug, stretchy fit for ultimate flexibility during yoga or gym sessions. Made with Dri-FIT technology, they wick away sweat and feature a high-waisted design for added comfort and coverage.',
                'photo' => '',
                'stock' => 35,
                'size' => 'M',
                'condition' => 'default',
                'status' => 'active',
                'price' => 50.00,
                'discount' => 0,
                'is_featured' => false,
                'cat_id' => 2,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Adidas Climalite Hoodie',
                'slug' => 'adidas-climalite-hoodie',
                'summary' => 'Warm hoodie for cool-weather workouts.',
                'description' => 'The Adidas Climalite Hoodie provides warmth and comfort for cool-weather training. Its moisture-wicking fabric keeps you dry, while the adjustable hood and kangaroo pocket add practicality and style for outdoor or casual wear.',
                'photo' => '',
                'stock' => 25,
                'size' => 'L',
                'condition' => 'new',
                'status' => 'active',
                'price' => 70.00,
                'discount' => 15.00,
                'is_featured' => false,
                'cat_id' => 2,
                'child_cat_id' => null,
                'brand_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Under Armour ColdGear Tights',
                'slug' => 'under-armour-coldgear-tights',
                'summary' => 'Insulated tights for winter sports.',
                'description' => 'The Under Armour ColdGear Tights are designed for cold-weather activities, featuring dual-layer fabric for warmth and moisture-wicking properties. Their compression fit supports muscle recovery, making them ideal for winter running or outdoor sports.',
                'photo' => '',
                'stock' => 20,
                'size' => 'S',
                'condition' => 'default',
                'status' => 'inactive',
                'price' => 55.00,
                'discount' => 0,
                'is_featured' => false,
                'cat_id' => 2,
                'child_cat_id' => null,
                'brand_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nike Sportswear Tank Top',
                'slug' => 'nike-sportswear-tank-top',
                'summary' => 'Sleeveless top for intense workouts.',
                'description' => 'The Nike Sportswear Tank Top is perfect for high-intensity workouts, featuring a lightweight, breathable design with Dri-FIT technology to keep you cool and dry. Its sleeveless cut allows for unrestricted movement during gym sessions or outdoor activities.',
                'photo' => '',
                'stock' => 40,
                'size' => 'M',
                'condition' => 'hot',
                'status' => 'active',
                'price' => 30.00,
                'discount' => 5.00,
                'is_featured' => true,
                'cat_id' => 2,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Adidas Essentials Sweatshirt',
                'slug' => 'adidas-essentials-sweatshirt',
                'summary' => 'Cozy sweatshirt for casual wear.',
                'description' => 'The Adidas Essentials Sweatshirt offers a relaxed fit and soft cotton-blend fabric for all-day comfort. Perfect for casual wear or light workouts, it features a classic crew neck and ribbed cuffs for a timeless look.',
                'photo' => '',
                'stock' => 30,
                'size' => 'L',
                'condition' => 'default',
                'status' => 'active',
                'price' => 65.00,
                'discount' => 0,
                'is_featured' => false,
                'cat_id' => 2,
                'child_cat_id' => null,
                'brand_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Under Armour Performance Polo',
                'slug' => 'under-armour-performance-polo',
                'summary' => 'Breathable polo shirt for sports.',
                'description' => 'The Under Armour Performance Polo combines style and functionality with its moisture-wicking HeatGear fabric and four-way stretch. Ideal for golf, tennis, or casual sports, it offers a comfortable fit and UV protection for outdoor activities.',
                'photo' => '',
                'stock' => 28,
                'size' => 'M',
                'condition' => 'new',
                'status' => 'active',
                'price' => 45.00,
                'discount' => 10.00,
                'is_featured' => false,
                'cat_id' => 2,
                'child_cat_id' => null,
                'brand_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nike Training Shorts',
                'slug' => 'nike-training-shorts',
                'summary' => 'Lightweight shorts for gym sessions.',
                'description' => 'The Nike Training Shorts are designed for intense workouts, featuring Dri-FIT technology to wick away sweat and a stretchy waistband for comfort. With side pockets and a lightweight design, they’re perfect for gym sessions or outdoor runs.',
                'photo' => '',
                'stock' => 35,
                'size' => 'S',
                'condition' => 'default',
                'status' => 'active',
                'price' => 38.00,
                'discount' => 0,
                'is_featured' => false,
                'cat_id' => 2,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Fitness Equipment (cat_id: 3)
            [
                'title' => 'Nike Yoga Mat',
                'slug' => 'nike-yoga-mat',
                'summary' => 'Non-slip yoga mat for stability.',
                'description' => 'The Nike Yoga Mat is designed for stability and comfort, featuring a non-slip surface and lightweight, portable design. Its textured surface provides excellent grip, making it ideal for yoga, pilates, or home workouts.',
                'photo' => '',
                'stock' => 15,
                'size' => 'N/A',
                'condition' => 'new',
                'status' => 'active',
                'price' => 50.00,
                'discount' => 5.00,
                'is_featured' => true,
                'cat_id' => 3,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Adidas Resistance Bands',
                'slug' => 'adidas-resistance-bands',
                'summary' => 'Set of resistance bands for strength training.',
                'description' => 'The Adidas Resistance Bands come in a set with varying resistance levels, perfect for strength training and muscle toning. Made from durable latex, they’re portable and versatile for home or gym workouts, targeting multiple muscle groups.',
                'photo' => '',
                'stock' => 20,
                'size' => 'N/A',
                'condition' => 'default',
                'status' => 'active',
                'price' => 25.00,
                'discount' => 0,
                'is_featured' => false,
                'cat_id' => 3,
                'child_cat_id' => null,
                'brand_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Under Armour Dumbbells',
                'slug' => 'under-armour-dumbbells',
                'summary' => 'Pair of adjustable dumbbells for home workouts.',
                'description' => 'The Under Armour Dumbbells are adjustable, allowing you to customize weights for various exercises. With a comfortable grip and durable construction, they’re perfect for home workouts, targeting strength and endurance training.',
                'photo' => '',
                'stock' => 10,
                'size' => 'N/A',
                'condition' => 'hot',
                'status' => 'active',
                'price' => 80.00,
                'discount' => 10.00,
                'is_featured' => false,
                'cat_id' => 3,
                'child_cat_id' => null,
                'brand_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nike Kettlebell',
                'slug' => 'nike-kettlebell',
                'summary' => 'Durable kettlebell for strength exercises.',
                'description' => 'The Nike Kettlebell is built for strength and functional training, featuring a cast-iron construction with a smooth handle for a secure grip. Ideal for swings, squats, and other exercises, it’s a versatile addition to any home gym.',
                'photo' => '',
                'stock' => 12,
                'size' => 'N/A',
                'condition' => 'default',
                'status' => 'active',
                'price' => 60.00,
                'discount' => 0,
                'is_featured' => false,
                'cat_id' => 3,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Adidas Jump Rope',
                'slug' => 'adidas-jump-rope',
                'summary' => 'High-speed jump rope for cardio workouts.',
                'description' => 'The Adidas Jump Rope features a high-speed design with adjustable length and comfortable handles. Perfect for cardio workouts, it helps improve coordination and endurance, making it a must-have for fitness enthusiasts.',
                'photo' => '',
                'stock' => 25,
                'size' => 'N/A',
                'condition' => 'new',
                'status' => 'active',
                'price' => 20.00,
                'discount' => 3.00,
                'is_featured' => false,
                'cat_id' => 3,
                'child_cat_id' => null,
                'brand_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Under Armour Foam Roller',
                'slug' => 'under-armour-foam-roller',
                'summary' => 'Textured foam roller for muscle recovery.',
                'description' => 'The Under Armour Foam Roller is designed for muscle recovery and flexibility, featuring a textured surface to target trigger points. Its compact design makes it easy to use at home or the gym, ideal for post-workout recovery.',
                'photo' => '',
                'stock' => 18,
                'size' => 'N/A',
                'condition' => 'default',
                'status' => 'active',
                'price' => 35.00,
                'discount' => 0,
                'is_featured' => false,
                'cat_id' => 3,
                'child_cat_id' => null,
                'brand_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nike Medicine Ball',
                'slug' => 'nike-medicine-ball',
                'summary' => 'Weighted ball for core and strength training.',
                'description' => 'The Nike Medicine Ball is perfect for core and strength exercises, featuring a textured surface for a secure grip. Available in multiple weights, it’s ideal for dynamic workouts, enhancing power and stability.',
                'photo' => '',
                'stock' => 15,
                'size' => 'N/A',
                'condition' => 'hot',
                'status' => 'active',
                'price' => 45.00,
                'discount' => 5.00,
                'is_featured' => true,
                'cat_id' => 3,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Adidas Gym Ball',
                'slug' => 'adidas-gym-ball',
                'summary' => 'Stability ball for balance and core exercises.',
                'description' => 'The Adidas Gym Ball is designed for balance and core training, featuring a durable, anti-burst material. Perfect for yoga, pilates, or strength exercises, it helps improve stability and posture in your workouts.',
                'photo' => '',
                'stock' => 20,
                'size' => 'N/A',
                'condition' => 'default',
                'status' => 'active',
                'price' => 30.00,
                'discount' => 0,
                'is_featured' => false,
                'cat_id' => 3,
                'child_cat_id' => null,
                'brand_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Under Armour Speed Rope',
                'slug' => 'under-armour-speed-rope',
                'summary' => 'Adjustable speed rope for intense cardio.',
                'description' => 'The Under Armour Speed Rope features a lightweight, adjustable design for high-intensity cardio workouts. Its ergonomic handles ensure a comfortable grip, making it ideal for improving speed, agility, and endurance.',
                'photo' => '',
                'stock' => 22,
                'size' => 'N/A',
                'condition' => 'new',
                'status' => 'active',
                'price' => 25.00,
                'discount' => 3.00,
                'is_featured' => false,
                'cat_id' => 3,
                'child_cat_id' => null,
                'brand_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nike Push-Up Grips',
                'slug' => 'nike-push-up-grips',
                'summary' => 'Ergonomic grips for push-up exercises.',
                'description' => 'The Nike Push-Up Grips are designed to enhance push-up workouts, featuring ergonomic handles to reduce wrist strain. Their non-slip base ensures stability, making them perfect for strength training at home or in the gym.',
                'photo' => '',
                'stock' => 18,
                'size' => 'N/A',
                'condition' => 'default',
                'status' => 'active',
                'price' => 20.00,
                'discount' => 0,
                'is_featured' => false,
                'cat_id' => 3,
                'child_cat_id' => null,
                'brand_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
